### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Ghayyas** [arafatamim/ticker_text#1]
The text is not scrolling(Moving).

**Comment by arafatamim** [comment]
Please provide a **reprex** (minimal reproducible example), and a detailed explanation of the problem you're facing so I can pin down the issue

**Comment by arafatamim** [comment]
Closed due to inactivity.

**Comment by Ghayyas** [comment]
I have tried the given example as you provided but the text is not moving. Can you provide and other example in flutter

**Comment by arafatamim** [comment]
I'm sorry if this wasn't implicitly understood, but you need to wrap the `TickerText` widget in a constrained layout widget such as `SizedBox` with a specific height/width so it doesn't fill out the entire container. I'll update the docs to make it more clear.
